import { StyleSheet } from 'react-native';
import { colors } from './colors';

const cardShadow = {
  shadowColor: colors.authTitle,
  shadowOpacity: 0.08,
  shadowRadius: 18,
  shadowOffset: { width: 0, height: 8 },
  elevation: 5,
};

const softShadow = {
  shadowColor: colors.authTitle,
  shadowOpacity: 0.05,
  shadowRadius: 10,
  shadowOffset: { width: 0, height: 4 },
  elevation: 2,
};

export const authStyles = StyleSheet.create({
  safeScreen: {
    flex: 1,
    backgroundColor: colors.authBackground,
  },
  keyboard: {
    flex: 1,
  },
  centeredScrollContent: {
    flexGrow: 1,
    justifyContent: 'center',
    paddingHorizontal: 20,
    paddingVertical: 28,
  },
  topScrollContent: {
    flexGrow: 1,
    paddingHorizontal: 16,
    paddingTop: 16,
    paddingBottom: 40,
  },
  heroHeader: {
    alignItems: 'center',
    marginBottom: 28,
    paddingHorizontal: 22,
  },
  heroBadge: {
    width: 96,
    height: 96,
    borderRadius: 48,
    alignItems: 'center',
    justifyContent: 'center',
    backgroundColor: colors.authCard,
    borderWidth: 2.5,
    borderColor: 'rgba(255, 255, 255, 0.96)',
    overflow: 'hidden',
    marginBottom: 16,
    shadowColor: colors.authTitleAccent,
    shadowOpacity: 0.16,
    shadowRadius: 14,
    shadowOffset: { width: 0, height: 6 },
    elevation: 4,
  },
  heroBadgeImage: {
    width: '100%',
    height: '100%',
    borderRadius: 48,
  },
  heroFrame: {
    width: '100%',
    height: 180,
    borderRadius: 24,
    borderWidth: 1.5,
    borderColor: colors.authWarmLine,
    backgroundColor: colors.authHeroSurface,
    overflow: 'hidden',
    ...softShadow,
  },
  heroFrameInner: {
    flex: 1,
    alignItems: 'center',
    justifyContent: 'center',
    backgroundColor: colors.authHeroSurface,
  },
  heroFrameImage: {
    width: '100%',
    height: '100%',
  },
  centeredTitle: {
    fontSize: 34,
    fontWeight: '800',
    lineHeight: 40,
    textAlign: 'center',
    color: colors.authTitle,
    letterSpacing: -0.5,
  },
  cardTitle: {
    fontSize: 30,
    fontWeight: '800',
    lineHeight: 36,
    color: colors.authTitle,
    letterSpacing: -0.4,
  },
  titleAccent: {
    color: colors.authTitleAccent,
  },
  centeredSubtitle: {
    marginTop: 10,
    textAlign: 'center',
    color: colors.authBody,
    fontSize: 17,
    lineHeight: 25,
    maxWidth: 320,
  },
  cardSubtitle: {
    marginTop: 10,
    marginBottom: 22,
    color: colors.authBody,
    fontSize: 17,
    lineHeight: 25,
  },
  formShell: {
    backgroundColor: colors.authCardTint,
    borderRadius: 28,
    paddingVertical: 18,
    paddingHorizontal: 6,
    marginHorizontal: 12,
    borderWidth: 1,
    borderColor: '#E2F0F5',
  },
  stackCard: {
    marginHorizontal: 6,
  },
  inputRow: {
    flexDirection: 'row',
    alignItems: 'center',
    backgroundColor: colors.authCard,
    borderWidth: 1.25,
    borderColor: colors.authInputBorder,
    borderRadius: 16,
    paddingHorizontal: 16,
    minHeight: 58,
    marginVertical: 8,
    ...softShadow,
  },
  inputIcon: {
    width: 20,
    height: 20,
    tintColor: colors.authInputIcon,
  },
  inputText: {
    flex: 1,
    color: colors.authTitle,
    fontSize: 17,
    paddingVertical: 0,
  },
  fieldLabel: {
    marginBottom: 8,
    color: colors.authTitle,
    fontWeight: '700',
    fontSize: 15,
  },
  textInput: {
    borderWidth: 1.25,
    borderColor: colors.authInputBorder,
    borderRadius: 16,
    paddingHorizontal: 16,
    paddingVertical: 14,
    marginBottom: 14,
    backgroundColor: colors.authCard,
    color: colors.authTitle,
    fontSize: 17,
    ...softShadow,
  },
  disabledInput: {
    backgroundColor: '#F8FBFD',
    color: colors.authBody,
  },
  button: {
    width: '100%',
    borderRadius: 18,
    backgroundColor: colors.authPrimaryButton,
    paddingVertical: 15,
    alignItems: 'center',
    justifyContent: 'center',
    ...cardShadow,
  },
  buttonPressed: {
    backgroundColor: colors.authPrimaryButtonPressed,
  },
  buttonDisabled: {
    opacity: 0.72,
  },
  buttonText: {
    color: colors.white,
    fontSize: 18,
    fontWeight: '800',
  },
  primaryActionWrap: {
    marginTop: 24,
    alignItems: 'center',
  },
  link: {
    marginTop: 16,
    textAlign: 'center',
    color: colors.authLink,
    fontWeight: '700',
  },
  secondaryLink: {
    marginTop: 12,
    textAlign: 'center',
    color: colors.authBody,
    fontWeight: '500',
  },
  helperText: {
    textAlign: 'center',
    color: colors.authBody,
    lineHeight: 24,
    maxWidth: 300,
  },
  footerText: {
    marginTop: 22,
    textAlign: 'center',
    color: colors.authBody,
    lineHeight: 24,
  },
  inlineLink: {
    color: colors.authLink,
    fontWeight: '700',
  },
  sectionLabel: {
    marginBottom: 10,
    color: colors.authTitle,
    fontWeight: '700',
    fontSize: 16,
  },
  roleRow: {
    flexDirection: 'row',
    gap: 12,
  },
  roleCard: {
    flex: 1,
    borderRadius: 18,
    borderWidth: 1.5,
    borderColor: colors.authInputBorder,
    backgroundColor: colors.authCard,
    paddingVertical: 16,
    paddingHorizontal: 14,
  },
  roleCardActive: {
    borderColor: colors.authPrimaryButton,
    backgroundColor: colors.authCardTint,
    shadowColor: colors.authSoftAccent,
    shadowOpacity: 0.18,
    shadowRadius: 8,
    shadowOffset: { width: 0, height: 4 },
    elevation: 3,
  },
  roleTitle: {
    color: colors.authTitle,
    fontWeight: '800',
    textAlign: 'center',
    fontSize: 15,
  },
  roleDescription: {
    marginTop: 6,
    color: colors.authBody,
    fontSize: 12,
    lineHeight: 18,
    textAlign: 'center',
  },
  checkboxRow: {
    flexDirection: 'row',
    alignItems: 'flex-start',
    marginTop: 12,
    paddingRight: 16,
    paddingLeft: 10,
  },
  checkbox: {
    marginRight: 10,
    width: 20,
    height: 20,
    borderRadius: 5,
    borderColor: colors.authInputBorder,
  },
  checkboxText: {
    flex: 1,
    lineHeight: 22,
    color: colors.authBody,
  },
  noteText: {
    marginTop: 16,
    textAlign: 'center',
    color: colors.authBody,
    lineHeight: 22,
  },
  cardSurface: {
    backgroundColor: colors.authCard,
    borderRadius: 28,
    padding: 24,
    borderWidth: 1,
    borderColor: '#E5EFF5',
    ...cardShadow,
  },
});
