export const PROFILE_AVATAR_CONTAINER_SIZE = 160;
export const PROFILE_AVATAR_FRAME_SIZE = 150;
export const PROFILE_AVATAR_BORDER_WIDTH = 3;
export const PROFILE_AVATAR_ACTION_SIZE = 42;
export const PROFILE_AVATAR_ACTION_INSET = 12;
export const PROFILE_AVATAR_INNER_SIZE =
  PROFILE_AVATAR_FRAME_SIZE - PROFILE_AVATAR_BORDER_WIDTH * 2;

export const PROFILE_AVATAR_FRAME_RADIUS = PROFILE_AVATAR_FRAME_SIZE / 2;
export const PROFILE_AVATAR_INNER_RADIUS = PROFILE_AVATAR_INNER_SIZE / 2;
export const PROFILE_AVATAR_ACTION_RADIUS = PROFILE_AVATAR_ACTION_SIZE / 2;
